(function(){
  'use strict';
  const esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const money=n=>'S/ '+Number(n||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2});
  const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Lima'});
  const parseDate=s=>s?new Date(s+'T00:00:00'):null;
  const dateLabel=s=>{const d=parseDate(s);return d?d.toLocaleDateString('es-PE',{day:'2-digit',month:'short',year:'numeric'}):'—'};
  const getState=()=>window._profileState||{appointments:[],patients:[],histories:[],notes:[]};
  const byPatient=id=>getState().patients.find(p=>String(p.id)===String(id));
  const pName=a=>a.patientName||(byPatient(a.patientId)||{}).name||'Paciente';
  const icon=n=>`<svg class="v2-icon"><use href="#i-${n}"></use></svg>`;
  const statusLabel=s=>({pendiente:'Agendada',confirmada:'Confirmada',arrived:'Llegó',in_session:'En sesión',completada:'Completada',cancelada:'Cancelada',no_asistio:'No asistió'}[s]||s||'Agendada');
  const statusTone=s=>({pendiente:'amber',confirmada:'blue',arrived:'cyan',in_session:'violet',completada:'green',cancelada:'slate',no_asistio:'orange'}[s]||'amber');
  const crmKey=p=>{const s=p.leadStatus||'nuevo';return ['atendido','recurrente'].includes(s)?'tratamiento':s==='cancelo'?'pausado':s==='no_asistio'?'seguimiento':s};
  const crmLabel=p=>({nuevo:'Nuevo',contactado:'Contactado',interesado:'Interesado',cita_agendada:'Primera cita',atendido:'En tratamiento',recurrente:'En tratamiento',no_asistio:'Seguimiento',cancelo:'Pausado',seguimiento:'Seguimiento',pausado:'Pausado',alta:'Alta',inactivo:'Inactivo'}[p.leadStatus]||'Nuevo');
  function daysBetween(a,b){return Math.floor((b-a)/86400000)}
  function patientApps(pid){return (getState().appointments||[]).filter(a=>String(a.patientId)===String(pid))}
  function lastAppointment(pid){return patientApps(pid).filter(a=>a.status!=='cancelada').sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0]}
  function nextAppointment(pid){const t=today();return patientApps(pid).filter(a=>(a.date||'')>=t&&!['cancelada','no_asistio'].includes(a.status)).sort((a,b)=>(a.date||'').localeCompare(b.date||'')||String(a.time||'').localeCompare(String(b.time||'')))[0]}
  function pendingForPatient(pid){return patientApps(pid).filter(a=>a.status!=='cancelada'&&(a.paymentStatus||'pendiente')!=='pagado').reduce((s,a)=>s+Number(a.cost||0),0)}
  function kpi(label,value,ico,sub=''){return `<div class="v2-kpi v2-kpi-compact"><span class="v2-kpi-icon">${icon(ico)}</span><div><div class="v2-kpi-value">${esc(value)}</div><div class="v2-kpi-label mt-2">${esc(label)}</div>${sub?`<div class="v2-kpi-sub">${esc(sub)}</div>`:''}</div></div>`}
  function empty(msg){return `<div class="v2-empty">${icon('file')}<span>${esc(msg)}</span></div>`}

  window.exportAgendaBackup=function(){const s=getState();const payload={version:'psicologia-pro-v2.2',exportedAt:new Date().toISOString(),appId:'psicologia-agenda-default-v2',appointments:s.appointments||[],patients:s.patients||[],clinicalHistories:s.histories||[],clinicalNotes:s.notes||[]};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`respaldo-psicologia-${today()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};

  window.renderV2Dashboard=function(){
    const s=getState(),root=document.getElementById('sec-inicio');if(!root)return;const t=today();const apps=(s.appointments||[]).filter(a=>a.date===t).sort((a,b)=>String(a.time||'').localeCompare(String(b.time||'')));
    const completed=apps.filter(a=>a.status==='completada').length,pending=apps.filter(a=>!['completada','cancelada','no_asistio'].includes(a.status)).length,cancelled=apps.filter(a=>['cancelada','no_asistio'].includes(a.status)).length;
    const collected=apps.filter(a=>a.status!=='cancelada'&&a.paymentStatus==='pagado').reduce((x,a)=>x+Number(a.cost||0),0);const receivable=(s.appointments||[]).filter(a=>a.status==='completada'&&a.paymentStatus!=='pagado').reduce((x,a)=>x+Number(a.cost||0),0);
    const patients=s.patients||[],now=new Date(),monthPrefix=t.slice(0,7);const newMonth=patients.filter(p=>{const own=patientApps(p.id).filter(a=>a.date).sort((a,b)=>String(a.date).localeCompare(String(b.date)));return String(own[0]?.date||'').startsWith(monthPrefix)}).length;
    const untracked=patients.filter(p=>{const la=lastAppointment(p.id);if(!la)return false;const d=parseDate(la.date);return d&&daysBetween(d,now)>30&&!nextAppointment(p.id)&&!['alta','inactivo'].includes(crmKey(p))}).slice(0,5);
    const packageAlerts=[];patients.forEach(p=>(p.packages||[]).forEach(pk=>{const total=Number(pk.sessionsTotal||pk.sessions||pk.totalSessions||pk.total||0),used=Number(pk.sessionsUsed||pk.usedSessions||pk.used||0);if(total&&Math.max(total-used,0)===1)packageAlerts.push({p,pk})}));
    const unpaidPatients=patients.map(p=>({p,amount:pendingForPatient(p.id)})).filter(x=>x.amount>0).sort((a,b)=>b.amount-a.amount).slice(0,4);
    const set=(id,val)=>{const e=document.getElementById(id);if(e)e.textContent=val};set('v2-kpi-today',apps.length);set('v2-kpi-completed',completed);set('v2-kpi-pending',pending);set('v2-kpi-cancelled',cancelled);set('v2-kpi-collected',money(collected));set('v2-kpi-receivable',money(receivable));set('v2-kpi-patients',patients.length);set('v2-kpi-new',newMonth);
    const list=document.getElementById('v2-today-list');if(list)list.innerHTML=apps.length?apps.map(a=>`<div class="v2-appointment-row"><div class="v2-time">${esc(a.time||'--:--')}</div><div class="min-w-0"><div class="text-sm font-extrabold text-slate-700 truncate">${esc(pName(a))}</div><div class="text-[11px] text-slate-400 mt-0.5">${esc(a.attentionType||a.type||'Sesión')} · ${esc(a.modality||'Sin modalidad')} · ${money(a.cost)}</div></div><span class="v2-status tone-${statusTone(a.status)}">${esc(statusLabel(a.status))}</span></div>`).join(''):empty('No hay citas programadas para hoy.');
    const alerts=document.getElementById('v2-alerts');if(alerts){const arr=[];if(unpaidPatients.length)arr.push(`<button onclick="switchTab('alertas')" class="v2-alert">${icon('money')}<div><strong>${unpaidPatients.length} paciente(s) con pagos pendientes</strong><span>${money(unpaidPatients.reduce((x,i)=>x+i.amount,0))} en seguimiento.</span></div></button>`);if(untracked.length)arr.push(`<button onclick="switchTab('alertas')" class="v2-alert">${icon('bell')}<div><strong>${untracked.length} paciente(s) sin seguimiento</strong><span>Más de 30 días sin próxima cita.</span></div></button>`);if(packageAlerts.length)arr.push(`<button onclick="switchTab('alertas')" class="v2-alert">${icon('clock')}<div><strong>${packageAlerts.length} paquete(s) por terminar</strong><span>Queda una sesión disponible.</span></div></button>`);if(!arr.length)arr.push(`<div class="v2-alert">${icon('check')}<div><strong>Todo en orden</strong><span>No hay alertas operativas prioritarias.</span></div></div>`);alerts.innerHTML=arr.join('')}
    const greet=document.getElementById('v2-greeting');if(greet){const h=new Date().getHours();greet.textContent=h<12?'Buenos días':h<19?'Buenas tardes':'Buenas noches'}const fd=document.getElementById('v2-full-date');if(fd)fd.textContent=new Date().toLocaleDateString('es-PE',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
  };

  window.renderV2Reception=function(){const s=getState(),input=document.getElementById('v2-reception-date');if(!input)return;if(!input.value)input.value=today();const d=input.value,apps=(s.appointments||[]).filter(a=>a.date===d).sort((a,b)=>String(a.time||'').localeCompare(String(b.time||'')));const active=apps.filter(a=>!['cancelada','no_asistio','completada'].includes(a.status)).length;const waiting=apps.filter(a=>a.status==='arrived').length;const inSession=apps.filter(a=>a.status==='in_session').length;const done=apps.filter(a=>a.status==='completada').length;const pendingPay=apps.filter(a=>a.status==='completada'&&a.paymentStatus!=='pagado').reduce((x,a)=>x+Number(a.cost||0),0);document.getElementById('v2-reception-kpis').innerHTML=kpi('Citas',apps.length,'calendar')+kpi('Por atender',active,'clock')+kpi('En espera',waiting,'reception')+kpi('En sesión',inSession,'clinical')+kpi('Pendiente cobro',money(pendingPay),'money');const root=document.getElementById('v2-reception-list');if(!apps.length){root.innerHTML=empty('No hay citas para esta fecha.');return}const nextMap={pendiente:['confirmada','Confirmar'],confirmada:['arrived','Registrar llegada'],arrived:['in_session','Iniciar sesión'],in_session:['completada','Completar sesión']};root.innerHTML=apps.map(a=>{const next=nextMap[a.status];return `<div class="v2-reception-row"><div class="v2-reception-time">${esc(a.time||'--:--')}</div><div class="v2-reception-main"><div class="flex items-center gap-2 flex-wrap"><strong>${esc(pName(a))}</strong><span class="v2-status tone-${statusTone(a.status)}">${esc(statusLabel(a.status))}</span>${a.paymentStatus==='pagado'?'<span class="v2-paid">Pagado</span>':'<span class="v2-unpaid">Pendiente</span>'}</div><span>${esc(a.attentionType||'Sesión')} · ${esc(a.modality||'')} · ${money(a.cost)}</span></div><div class="v2-reception-actions">${next?`<button class="v2-primary-btn sm" onclick="updateAppointmentStatus('${a.id}','${next[0]}').then(()=>renderV2Reception())">${icon('arrow')}${next[1]}</button>`:''}<button class="v2-secondary-btn sm" onclick="quickTogglePayment('${a.id}').then(()=>renderV2Reception())">${icon('money')}${a.paymentStatus==='pagado'?'Marcar pendiente':'Registrar pago'}</button><button class="v2-icon-btn" title="Editar cita" onclick="editAppointment('${a.id}')">${icon('edit')}</button>${!['cancelada','completada'].includes(a.status)?`<button class="v2-icon-btn danger" title="No asistió" onclick="updateAppointmentStatus('${a.id}','no_asistio').then(()=>renderV2Reception())">${icon('x')}</button>`:''}</div></div>`}).join('')};

  window.renderV2CRM=function(){const s=getState(),root=document.getElementById('v2-crm-table');if(!root)return;const f=document.getElementById('v2-crm-filter')?.value||'todos',q=(document.getElementById('v2-crm-search')?.value||'').toLowerCase();let rows=(s.patients||[]).map(p=>{const last=lastAppointment(p.id),next=nextAppointment(p.id),debt=pendingForPatient(p.id);return {p,last,next,debt,key:crmKey(p)}});if(f!=='todos')rows=rows.filter(r=>r.key===f);if(q)rows=rows.filter(r=>(r.p.name||'').toLowerCase().includes(q)||(r.p.phone||'').toLowerCase().includes(q)||(r.p.dni||'').toLowerCase().includes(q));const patients=s.patients||[],follow=patients.filter(p=>{const l=lastAppointment(p.id),d=l&&parseDate(l.date);return d&&daysBetween(d,new Date())>30&&!nextAppointment(p.id)&&!['alta','inactivo'].includes(crmKey(p))}).length;document.getElementById('v2-crm-summary').innerHTML=kpi('Pacientes',patients.length,'users')+kpi('En tratamiento',patients.filter(p=>crmKey(p)==='tratamiento').length,'clinical')+kpi('Seguimiento',follow,'bell')+kpi('Con deuda',patients.filter(p=>pendingForPatient(p.id)>0).length,'money');if(!rows.length){root.innerHTML=empty('No hay pacientes con estos filtros.');return}root.innerHTML=`<table class="v2-table"><thead><tr><th>Paciente</th><th>Estado CRM</th><th>Última sesión</th><th>Próxima cita</th><th>Saldo</th><th></th></tr></thead><tbody>${rows.sort((a,b)=>(a.p.name||'').localeCompare(b.p.name||'')).map(r=>`<tr><td><strong>${esc(r.p.name||'Paciente')}</strong><span>${esc(r.p.phone||r.p.dni||'Sin contacto')}</span></td><td><select class="v2-inline-select" onchange="updatePatientCRMStatus('${r.p.id}',this.value).then(()=>renderV2CRM())"><option value="nuevo" ${r.key==='nuevo'?'selected':''}>Nuevo</option><option value="contactado" ${r.key==='contactado'?'selected':''}>Contactado</option><option value="interesado" ${r.key==='interesado'?'selected':''}>Interesado</option><option value="cita_agendada" ${r.key==='cita_agendada'?'selected':''}>Primera cita</option><option value="recurrente" ${r.key==='tratamiento'?'selected':''}>En tratamiento</option><option value="seguimiento" ${r.key==='seguimiento'?'selected':''}>Seguimiento</option><option value="pausado" ${r.key==='pausado'?'selected':''}>Pausado</option><option value="alta" ${r.key==='alta'?'selected':''}>Alta</option><option value="inactivo" ${r.key==='inactivo'?'selected':''}>Inactivo</option></select></td><td>${r.last?dateLabel(r.last.date):'—'}</td><td>${r.next?`${dateLabel(r.next.date)} · ${esc(r.next.time||'')}`:'—'}</td><td class="${r.debt>0?'v2-debt':''}">${money(r.debt)}</td><td><button class="v2-link-btn" onclick="openPatient360('${r.p.id}')">Ver 360 ${icon('arrow')}</button></td></tr>`).join('')}</tbody></table>`};

  window.renderV2Clinical=function(){const s=getState(),root=document.getElementById('v2-clinical-table');if(!root)return;const q=(document.getElementById('v2-clinical-search')?.value||'').toLowerCase(),histIds=new Set((s.histories||[]).map(h=>String(h.id))),notesBy={};(s.notes||[]).forEach(n=>{const id=String(n.patientId||n.pid||'');notesBy[id]=(notesBy[id]||0)+1});let patients=(s.patients||[]).filter(p=>!q||(p.name||'').toLowerCase().includes(q));const withHist=patients.filter(p=>histIds.has(String(p.id))).length;document.getElementById('v2-clinical-kpis').innerHTML=kpi('Pacientes',patients.length,'users')+kpi('Con historia',withHist,'clinical')+kpi('Historia pendiente',Math.max(patients.length-withHist,0),'file')+kpi('Notas clínicas',(s.notes||[]).length,'report');if(!patients.length){root.innerHTML=empty('No hay pacientes para mostrar.');return}root.innerHTML=`<table class="v2-table"><thead><tr><th>Paciente</th><th>Historia clínica</th><th>Notas</th><th>Última sesión</th><th>Acciones</th></tr></thead><tbody>${patients.map(p=>{const has=histIds.has(String(p.id)),last=lastAppointment(p.id),n=notesBy[String(p.id)]||0;return `<tr><td><strong>${esc(p.name||'Paciente')}</strong><span>${esc(p.phone||'')}</span></td><td><span class="v2-status ${has?'tone-green':'tone-amber'}">${has?'Registrada':'Pendiente'}</span></td><td>${n}</td><td>${last?dateLabel(last.date):'—'}</td><td><div class="flex gap-2"><button class="v2-secondary-btn sm" onclick="openClinicalHistory('${p.id}')">${icon('clinical')}Abrir historia</button><button class="v2-link-btn" onclick="openPatient360('${p.id}')">Ficha 360</button></div></td></tr>`}).join('')}</tbody></table>`};

  window.renderV2Cash=function(){const s=getState(),input=document.getElementById('v2-cash-date');if(!input)return;if(!input.value)input.value=today();const d=input.value,apps=(s.appointments||[]).filter(a=>a.date===d&&a.status!=='cancelada'),paid=apps.filter(a=>a.paymentStatus==='pagado'),pending=apps.filter(a=>a.status==='completada'&&a.paymentStatus!=='pagado'),income=paid.reduce((x,a)=>x+Number(a.cost||0),0),due=pending.reduce((x,a)=>x+Number(a.cost||0),0),projected=apps.filter(a=>a.status!=='no_asistio').reduce((x,a)=>x+Number(a.cost||0),0);document.getElementById('v2-cash-kpis').innerHTML=kpi('Cobrado',money(income),'money')+kpi('Pendiente',money(due),'wallet')+kpi('Proyección día',money(projected),'report')+kpi('Operaciones pagadas',paid.length,'check');const renderRows=list=>list.length?list.sort((a,b)=>String(a.time||'').localeCompare(String(b.time||''))).map(a=>`<div class="v2-money-row"><div><strong>${esc(pName(a))}</strong><span>${esc(a.time||'')} · ${esc(a.modality||'')}</span></div><b>${money(a.cost)}</b></div>`).join(''):empty('Sin movimientos para esta fecha.');document.getElementById('v2-cash-paid').innerHTML=renderRows(paid);document.getElementById('v2-cash-pending').innerHTML=pending.length?pending.map(a=>`<div class="v2-money-row"><div><strong>${esc(pName(a))}</strong><span>${esc(a.time||'')} · sesión completada</span></div><button class="v2-secondary-btn sm" onclick="quickTogglePayment('${a.id}').then(()=>renderV2Cash())">Cobrar ${money(a.cost)}</button></div>`).join(''):empty('No hay cobros pendientes del día.')};

  window.renderV2Alerts=function(){const s=getState(),patients=s.patients||[],now=new Date(),histIds=new Set((s.histories||[]).map(h=>String(h.id)));const overdue=patients.map(p=>({p,amount:patientApps(p.id).filter(a=>a.status==='completada'&&a.paymentStatus!=='pagado').reduce((x,a)=>x+Number(a.cost||0),0)})).filter(x=>x.amount>0).sort((a,b)=>b.amount-a.amount);const follow=patients.map(p=>({p,last:lastAppointment(p.id)})).filter(x=>{const d=x.last&&parseDate(x.last.date);return d&&daysBetween(d,now)>30&&!nextAppointment(x.p.id)&&!['alta','inactivo'].includes(crmKey(x.p))});const incomplete=patients.filter(p=>!histIds.has(String(p.id)));const packages=[];patients.forEach(p=>(p.packages||[]).forEach(pk=>{const total=Number(pk.sessionsTotal||pk.sessions||pk.totalSessions||pk.total||0),used=Number(pk.sessionsUsed||pk.usedSessions||pk.used||0);if(total&&Math.max(total-used,0)<=1&&Math.max(total-used,0)>=0)packages.push({p,remaining:Math.max(total-used,0)})}));document.getElementById('v2-alert-kpis').innerHTML=kpi('Cobros vencidos',overdue.length,'money')+kpi('Sin seguimiento',follow.length,'bell')+kpi('Historias pendientes',incomplete.length,'file')+kpi('Paquetes por terminar',packages.length,'clock');const group=(title,ico,items,render)=>`<div class="v2-panel p-4 md:p-5"><div class="flex items-center gap-2 mb-3"><span class="v2-mini-icon">${icon(ico)}</span><h3 class="v2-section-title">${title}</h3></div>${items.length?items.slice(0,12).map(render).join(''):empty('Sin alertas en esta categoría.')}</div>`;document.getElementById('v2-alert-center').innerHTML=group('Cobros pendientes','money',overdue,x=>`<div class="v2-alert-line"><div><strong>${esc(x.p.name)}</strong><span>${money(x.amount)} pendiente</span></div><button class="v2-link-btn" onclick="openPatient360('${x.p.id}')">Ver ficha</button></div>`)+group('Seguimiento clínico','bell',follow,x=>`<div class="v2-alert-line"><div><strong>${esc(x.p.name)}</strong><span>Última sesión: ${x.last?dateLabel(x.last.date):'—'}</span></div><button class="v2-link-btn" onclick="markPatientFollowUp('${x.p.id}').then(()=>renderV2Alerts())">Marcar seguimiento</button></div>`)+group('Historia clínica pendiente','file',incomplete,p=>`<div class="v2-alert-line"><div><strong>${esc(p.name)}</strong><span>Sin historia clínica registrada</span></div><button class="v2-link-btn" onclick="openClinicalHistory('${p.id}')">Completar</button></div>`)+group('Paquetes por terminar','clock',packages,x=>`<div class="v2-alert-line"><div><strong>${esc(x.p.name)}</strong><span>${x.remaining===0?'Paquete agotado':'Queda 1 sesión'}</span></div><button class="v2-link-btn" onclick="openPatient360('${x.p.id}')">Ver paquete</button></div>`)};

  window.openPatient360=function(pid){const s=getState(),p=s.patients.find(x=>String(x.id)===String(pid));if(!p)return;const apps=patientApps(pid).sort((a,b)=>(b.date||'').localeCompare(a.date||'')||String(b.time||'').localeCompare(String(a.time||''))),completed=apps.filter(a=>a.status==='completada').length,next=nextAppointment(pid),last=lastAppointment(pid),debt=pendingForPatient(pid),hist=(s.histories||[]).find(h=>String(h.id)===String(pid)),notes=(s.notes||[]).filter(n=>String(n.patientId||n.pid||'')===String(pid));document.getElementById('p360-name').textContent=p.name||'Paciente';document.getElementById('p360-status').textContent=crmLabel(p);document.getElementById('p360-phone').textContent=p.phone||'—';document.getElementById('p360-birth').textContent=p.birth||'—';document.getElementById('p360-sessions').textContent=completed;document.getElementById('p360-debt').textContent=money(debt);document.getElementById('p360-last').textContent=last?dateLabel(last.date):'Sin sesiones';document.getElementById('p360-next').textContent=next?`${dateLabel(next.date)} · ${next.time||''}`:'Sin próxima cita';document.getElementById('p360-clinical').textContent=hist?'Historia clínica registrada':'Historia clínica pendiente';document.getElementById('p360-notes').textContent=`${notes.length} nota(s) clínica(s)`;const pkgs=p.packages||[];document.getElementById('p360-packages').innerHTML=pkgs.length?pkgs.slice().reverse().map(pk=>{const total=Number(pk.sessionsTotal||pk.sessions||pk.totalSessions||pk.total||0),used=Number(pk.sessionsUsed||pk.usedSessions||pk.used||0);return `<div class="v2-360-card"><div class="text-xs font-extrabold text-slate-700">${esc(pk.name||pk.label||'Paquete')}</div><div class="text-[11px] text-slate-400 mt-1">Sesiones: ${used}${total?' / '+total:''}</div></div>`}).join(''):'<div class="text-sm text-slate-400">No tiene paquetes registrados.</div>';document.getElementById('p360-timeline').innerHTML=apps.slice(0,8).map(a=>`<div class="v2-timeline-item"><div class="text-xs font-extrabold text-slate-700">${dateLabel(a.date)} · ${esc(a.time||'')}</div><div class="text-[11px] text-slate-400">${esc(statusLabel(a.status))} · ${esc(a.modality||'')} · ${money(a.cost)}</div></div>`).join('')||'<div class="text-sm text-slate-400">Sin actividad registrada.</div>';document.getElementById('p360-open-history').onclick=()=>{closePatient360();window.openPatientHistory&&window.openPatientHistory(pid)};document.getElementById('p360-open-clinical').onclick=()=>{closePatient360();window.openClinicalHistory&&window.openClinicalHistory(pid)};document.getElementById('p360-edit').onclick=()=>{closePatient360();window.editPatient&&window.editPatient(pid)};const m=document.getElementById('patient-360-modal');m.classList.remove('hidden');m.classList.add('flex')};
  window.closePatient360=function(){const m=document.getElementById('patient-360-modal');if(m){m.classList.add('hidden');m.classList.remove('flex')}};

  function syncNav(target){document.querySelectorAll('[data-v2-nav]').forEach(b=>b.classList.toggle('v2-nav-active',b.dataset.v2Nav===target))}
  const oldSwitch=window.switchTab;
  window.switchTab=function(target){const all=['inicio','citas','recepcion','pacientes','clinica','finanzas','caja','alertas'];all.forEach(t=>document.getElementById('sec-'+t)?.classList.add('hidden'));const legacy=['citas','pacientes','finanzas'];if(legacy.includes(target)&&typeof oldSwitch==='function')oldSwitch(target);else{document.getElementById('sec-'+target)?.classList.remove('hidden')}syncNav(target);if(target==='inicio')renderV2Dashboard();if(target==='recepcion')renderV2Reception();if(target==='pacientes')setTimeout(renderV2CRM,0);if(target==='clinica')renderV2Clinical();if(target==='caja')renderV2Cash();if(target==='alertas')renderV2Alerts();try{localStorage.setItem('agendaV2LastTab',target)}catch(_){}};

  document.addEventListener('DOMContentLoaded',()=>{const d=today();['v2-reception-date','v2-cash-date'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=d});syncNav('inicio');setTimeout(()=>{window.switchTab('inicio');renderV2Dashboard()},300);setInterval(()=>{const visible=['inicio','recepcion','pacientes','clinica','caja','alertas'].find(t=>!document.getElementById('sec-'+t)?.classList.contains('hidden'));if(visible==='inicio')renderV2Dashboard();if(visible==='recepcion')renderV2Reception();if(visible==='pacientes')renderV2CRM();if(visible==='clinica')renderV2Clinical();if(visible==='caja')renderV2Cash();if(visible==='alertas')renderV2Alerts()},15000)});
})();
