(function(){
'use strict';
const q=(id)=>document.getElementById(id), esc=(v='')=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const S=()=>window._profileState||{appointments:[],patients:[],histories:[],notes:[]};
const limaToday=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Lima'});
const money=n=>'S/ '+Number(n||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2});
const dateLabel=s=>s?new Date(s+'T00:00:00').toLocaleDateString('es-PE',{day:'2-digit',month:'short',year:'numeric'}):'—';
const ico=n=>`<svg class="v2-icon"><use href="#i-${n}"></use></svg>`;
const patient=id=>S().patients.find(p=>String(p.id)===String(id));
const pName=a=>a.patientName||patient(a.patientId)?.name||'Paciente';
const patientApps=id=>S().appointments.filter(a=>String(a.patientId)===String(id)&&a.recordType!=='manual_block');
const isValidApp=a=>a&&a.recordType!=='manual_block';
const appStatus=s=>({pendiente:'Agendada',confirmada:'Confirmada',arrived:'Llegó',in_session:'En sesión',completada:'Completada',cancelada:'Cancelada',no_asistio:'No asistió'}[s]||s||'Agendada');
const statusTone=s=>({completada:'green',cancelada:'red',no_asistio:'red',confirmada:'blue',arrived:'blue',in_session:'amber'}[s]||'amber');
const ageDays=s=>s?Math.floor((new Date()-new Date(s+'T00:00:00'))/86400000):9999;
function toast(msg,type='ok'){let el=q('v3-toast');if(!el){el=document.createElement('div');el.id='v3-toast';el.style='position:fixed;right:18px;bottom:86px;z-index:120;padding:11px 14px;border-radius:12px;background:#173f39;color:white;font:700 11px Inter;box-shadow:0 15px 45px rgba(0,0,0,.2);opacity:0;transition:.2s';document.body.appendChild(el)}el.textContent=msg;el.style.background=type==='err'?'#8a3e4b':'#173f39';el.style.opacity='1';clearTimeout(window.__v3Toast);window.__v3Toast=setTimeout(()=>el.style.opacity='0',2400)}
function initials(name){return String(name||'P').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function completedCount(pid){return patientApps(pid).filter(a=>a.status==='completada').length}
function debt(pid){return patientApps(pid).filter(a=>!['cancelada','no_asistio'].includes(a.status)&&(a.paymentStatus||'pendiente')!=='pagado').reduce((n,a)=>n+Number(a.cost||0)-Number(a.paidAmount||0),0)}
function nextApp(pid){const t=limaToday();return patientApps(pid).filter(a=>a.date>=t&&!['cancelada','no_asistio','completada'].includes(a.status)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))[0]}
function lastApp(pid){return patientApps(pid).filter(a=>a.date&&a.status!=='cancelada').sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time))[0]}
function clinicalNoteCount(pid){return S().notes.filter(n=>String(n.patientId||n.pid||'')===String(pid)).length}
function hasHistory(pid){return S().histories.some(h=>String(h.id||h.patientId||'')===String(pid))}

function installShell(){
  document.title='Psicología Pro V3 · Gestión Integral';
  const ver=document.querySelector('.v2-brand-title span'); if(ver) ver.textContent='V3';
  const headerActions=document.querySelector('.v2-header-inner > div:last-child');
  if(headerActions&&!q('v3-global-search')){
    const search=document.createElement('div');search.className='v3-header-search';search.innerHTML=`${ico('search')}<input id="v3-global-search" placeholder="Buscar paciente, cita, teléfono..." readonly onclick="openV3Search()"><span class="v3-kbd">Ctrl K</span>`;
    headerActions.insertBefore(search,headerActions.firstChild);
    const add=document.createElement('button');add.className='v3-quick-add';add.innerHTML=`${ico('plus')}<span>Nuevo</span>`;add.onclick=()=>openV3Quick();headerActions.insertBefore(add,search.nextSibling);
  }
  const nav=document.querySelector('.v2-sidebar>div');
  if(nav&&!q('v3-nav-sesiones')){
    const ref=[...nav.querySelectorAll('button')].find(b=>b.dataset.v2Nav==='clinica');
    const btn=(id,target,icon,label)=>{const b=document.createElement('button');b.id=id;b.dataset.v2Nav=target;b.onclick=()=>window.switchTab(target);b.className='py-3 px-3 text-sm flex items-center gap-2';b.innerHTML=`${ico(icon)}<span>${label}</span>`;return b};
    ref?.after(btn('v3-nav-sesiones','sesiones','session','Sesiones'));
    const fin=[...nav.querySelectorAll('button')].find(b=>b.dataset.v2Nav==='finanzas');
    fin?.before(btn('v3-nav-evaluaciones','evaluaciones','test','Evaluaciones'));
    fin?.before(btn('v3-nav-documentos','documentos','folder','Documentos'));
  }
}
function injectSymbols(){const svg=document.querySelector('.v2-svg-sprite');if(!svg||q('v3-symbol-marker'))return;svg.insertAdjacentHTML('beforeend',`<symbol id="i-session" viewBox="0 0 24 24"><path d="M4 5h16v14H4z"/><path d="M8 9h8M8 13h5M8 17h3"/></symbol><symbol id="i-test" viewBox="0 0 24 24"><path d="M7 3h10v4H7z"/><path d="M5 5h14v16H5z"/><path d="m8 12 2 2 4-4M8 17h8"/></symbol><symbol id="i-folder" viewBox="0 0 24 24"><path d="M3 6h7l2 2h9v11H3z"/></symbol><symbol id="i-chart" viewBox="0 0 24 24"><path d="M4 20V10M10 20V4M16 20v-7M22 20V7"/></symbol><symbol id="i-command" viewBox="0 0 24 24"><path d="M9 6a3 3 0 1 1-3-3v15a3 3 0 1 1 3-3H6h12a3 3 0 1 1 3-3H6h12a3 3 0 1 1 0-6h-3v12a3 3 0 1 1-3 3V6z"/></symbol><g id="v3-symbol-marker"></g>`)}
function injectSections(){
 const main=document.querySelector('main'); if(!main)return;
 if(!q('sec-sesiones')) main.insertAdjacentHTML('beforeend',`<section id="sec-sesiones" class="space-y-5 hidden"><div class="v3-section-head"><div><span class="v3-eyebrow" style="color:#4f8e86">Práctica clínica</span><h2>Sesiones</h2><p>Convierte la cita en una unidad clínica: atención, evolución, cobro y continuidad.</p></div><div class="v3-head-actions"><button class="v3-secondary" onclick="switchTab('citas')">${ico('calendar')}Agenda</button><button class="v3-primary" onclick="openAppointmentModal()">${ico('plus')}Nueva cita</button></div></div><div id="v3-session-kpis" class="v3-kpi-grid"></div><div class="v3-card"><div class="v3-card-head"><div><h3>Registro de sesiones</h3><div class="v3-card-sub">Vista longitudinal de atenciones reales.</div></div><div class="v3-toolbar"><input id="v3-session-search" class="v3-input" placeholder="Buscar paciente..." oninput="renderV3Sessions()"><select id="v3-session-status" class="v3-select" onchange="renderV3Sessions()"><option value="all">Todos los estados</option><option value="completada">Completadas</option><option value="in_session">En sesión</option><option value="arrived">En espera</option><option value="confirmada">Confirmadas</option></select></div></div><div id="v3-session-table"></div></div></section>`);
 if(!q('sec-evaluaciones')) main.insertAdjacentHTML('beforeend',`<section id="sec-evaluaciones" class="space-y-5 hidden"><div class="v3-section-head"><div><span class="v3-eyebrow" style="color:#4f8e86">Medición clínica</span><h2>Evaluaciones</h2><p>Registra instrumentos y evolución sin modificar las historias ya almacenadas.</p></div><div class="v3-head-actions"><button class="v3-primary" onclick="openV3EvaluationModal()">${ico('plus')}Registrar evaluación</button></div></div><div id="v3-eval-kpis" class="v3-kpi-grid"></div><div class="v3-card"><div class="v3-card-head"><div><h3>Resultados registrados</h3><div class="v3-card-sub">PHQ-9, GAD-7, PSS, DASS-21 y pruebas personalizadas.</div></div><input id="v3-eval-search" class="v3-input" placeholder="Buscar paciente..." oninput="renderV3Evaluations()"></div><div id="v3-eval-table"></div></div></section>`);
 if(!q('sec-documentos')) main.insertAdjacentHTML('beforeend',`<section id="sec-documentos" class="space-y-5 hidden"><div class="v3-section-head"><div><span class="v3-eyebrow" style="color:#4f8e86">Expediente digital</span><h2>Documentos</h2><p>Organiza enlaces a consentimientos, informes, recetas y documentos externos por paciente.</p></div><div class="v3-head-actions"><button class="v3-primary" onclick="openV3DocumentModal()">${ico('plus')}Añadir documento</button></div></div><div id="v3-doc-kpis" class="v3-kpi-grid"></div><div class="v3-card"><div class="v3-card-head"><div><h3>Repositorio por paciente</h3><div class="v3-card-sub">Metadatos compatibles guardados en la ficha actual del paciente.</div></div><input id="v3-doc-search" class="v3-input" placeholder="Buscar..." oninput="renderV3Documents()"></div><div id="v3-doc-table"></div></div></section>`);
}
function installOverlays(){if(q('v3-command-overlay'))return;document.body.insertAdjacentHTML('beforeend',`
<div id="v3-command-overlay" class="v3-overlay hidden" onclick="if(event.target===this)closeV3Search()"><div class="v3-command"><div class="v3-command-search">${ico('search')}<input id="v3-command-input" placeholder="Busca pacientes, citas o escribe una acción..." oninput="renderV3SearchResults(this.value)"><span class="v3-kbd">ESC</span></div><div id="v3-command-results" class="v3-command-body"></div></div></div>
<div id="v3-drawer-backdrop" class="v3-drawer-backdrop hidden" onclick="closeV3Patient()"></div><aside id="v3-patient-drawer" class="v3-patient-drawer hidden"><div id="v3-patient-content"></div></aside>
<div id="v3-form-overlay" class="v3-overlay hidden" onclick="if(event.target===this)closeV3Form()"><div id="v3-form-modal" class="v3-modal"></div></div>`)}

window.openV3Search=function(){q('v3-command-overlay')?.classList.remove('hidden');const i=q('v3-command-input');if(i){i.value='';setTimeout(()=>i.focus(),30)}renderV3SearchResults('')};window.closeV3Search=()=>q('v3-command-overlay')?.classList.add('hidden');
window.renderV3SearchResults=function(term=''){const root=q('v3-command-results');if(!root)return;const t=term.trim().toLowerCase();let html='<div class="v3-command-group">Acciones rápidas</div>';const actions=[['Nueva cita','Crear una cita en la agenda','calendar',"closeV3Search();openAppointmentModal()"],['Nuevo paciente','Registrar paciente','users',"closeV3Search();openPatientModal()"],['Registrar evaluación','Añadir resultado clínico','test',"closeV3Search();openV3EvaluationModal()"],['Bloquear horario','Crear rango no disponible','lock',"closeV3Search();switchTab('citas');setTimeout(()=>openHorarioModal(),100)"],['Finanzas','Abrir análisis financiero','wallet',"closeV3Search();switchTab('finanzas')"]];
 actions.filter(x=>!t||x[0].toLowerCase().includes(t)||x[1].toLowerCase().includes(t)).forEach(x=>html+=`<button class="v3-command-item" onclick="${x[3]}"><span class="ico">${ico(x[2])}</span><span><strong>${x[0]}</strong><span>${x[1]}</span></span></button>`);
 const pats=S().patients.filter(p=>!t||[p.name,p.phone,p.dni].some(v=>String(v||'').toLowerCase().includes(t))).slice(0,8);if(pats.length){html+='<div class="v3-command-group">Pacientes</div>';pats.forEach(p=>html+=`<button class="v3-command-item" onclick="closeV3Search();openV3Patient('${p.id}')"><span class="ico">${ico('users')}</span><span><strong>${esc(p.name)}</strong><span>${esc(p.phone||p.dni||'Paciente registrado')}</span></span></button>`)}
 const apps=S().appointments.filter(isValidApp).filter(a=>t&&(pName(a)+' '+(a.date||'')+' '+(a.time||'')).toLowerCase().includes(t)).slice(0,6);if(apps.length){html+='<div class="v3-command-group">Citas</div>';apps.forEach(a=>html+=`<button class="v3-command-item" onclick="closeV3Search();editAppointment('${a.id}')"><span class="ico">${ico('calendar')}</span><span><strong>${esc(pName(a))}</strong><span>${dateLabel(a.date)} · ${esc(a.time||'')} · ${appStatus(a.status)}</span></span></button>`)}root.innerHTML=html||'<div class="v3-empty">Sin resultados.</div>'};
window.openV3Quick=function(){openV3Search();setTimeout(()=>{q('v3-command-input').placeholder='Elige o busca una acción…'},20)};

function kpi(label,val,icon,trend=''){return `<div class="v3-kpi"><div class="v3-kpi-top"><span class="v3-kpi-icon">${ico(icon)}</span>${trend?`<span class="v3-kpi-trend">${esc(trend)}</span>`:''}</div><div><div class="v3-kpi-value">${esc(val)}</div><div class="v3-kpi-label">${esc(label)}</div></div></div>`}
window.renderV3Dashboard=function(){const root=q('sec-inicio');if(!root)return;const st=S(),today=limaToday(),apps=st.appointments.filter(isValidApp),todayApps=apps.filter(a=>a.date===today).sort((a,b)=>String(a.time).localeCompare(String(b.time))),month=today.slice(0,7),monthApps=apps.filter(a=>String(a.date||'').startsWith(month)&&a.status!=='cancelada');const collected=monthApps.filter(a=>a.paymentStatus==='pagado').reduce((n,a)=>n+Number(a.cost||0),0),pending=apps.filter(a=>a.status==='completada'&&a.paymentStatus!=='pagado').reduce((n,a)=>n+Number(a.cost||0)-Number(a.paidAmount||0),0),active=st.patients.filter(p=>!['alta','inactivo'].includes(p.leadStatus)).length,waiting=todayApps.filter(a=>['arrived','in_session'].includes(a.status)).length;
 const last7=[...Array(7)].map((_,i)=>{const d=new Date(today+'T00:00:00');d.setDate(d.getDate()-(6-i));const ds=d.toLocaleDateString('en-CA');return {d,ds,val:apps.filter(a=>a.date===ds&&a.paymentStatus==='pagado'&&a.status!=='cancelada').reduce((n,a)=>n+Number(a.cost||0),0)}}),max=Math.max(1,...last7.map(x=>x.val));
 const noFollow=st.patients.map(p=>({p,last:lastApp(p.id),next:nextApp(p.id)})).filter(x=>x.last&&ageDays(x.last.date)>30&&!x.next&&!['alta','inactivo'].includes(x.p.leadStatus)).slice(0,4),unpaid=st.patients.map(p=>({p,amount:debt(p.id)})).filter(x=>x.amount>0).sort((a,b)=>b.amount-a.amount).slice(0,4);
 const nm=(window.getAgendaSpecialistFirstName?.()||'Lisbeth');root.innerHTML=`<div class="v3-shell"><div class="v3-hero"><div class="v3-hero-grid"><div><div class="v3-eyebrow">Panel de práctica clínica</div><h1>Buenos días, ${esc(nm)}</h1><p>${new Date().toLocaleDateString('es-PE',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}. Tienes ${todayApps.length} cita(s) y ${waiting} paciente(s) en flujo de atención.</p></div><div class="v3-hero-actions"><button class="v3-hero-btn" onclick="openAppointmentModal()">${ico('plus')}Nueva cita</button><button class="v3-hero-btn ghost" onclick="openV3Search()">${ico('search')}Buscar</button><button class="v3-hero-btn ghost" onclick="openAssistantModal()">${ico('spark')}Asistente IA</button></div></div></div>
 <div class="v3-kpi-grid">${kpi('Citas hoy',todayApps.length,'calendar')}${kpi('En flujo',waiting,'reception')}${kpi('Pacientes activos',active,'users')}${kpi('Cobrado este mes',money(collected),'money')}${kpi('Por cobrar',money(pending),'wallet')}${kpi('Historias pendientes',st.patients.filter(p=>!hasHistory(p.id)).length,'clinical')}</div>
 <div class="v3-grid-2"><div class="v3-card"><div class="v3-card-head"><div><h3>Agenda de hoy</h3><div class="v3-card-sub">Atenciones ordenadas por hora y estado.</div></div><button class="v3-link-btn" onclick="switchTab('citas')">Abrir agenda</button></div>${todayApps.length?todayApps.map(a=>`<div class="v3-agenda-row"><div class="v3-agenda-time">${esc(a.time||'--:--')}</div><div class="v3-agenda-line"></div><div><div class="v3-agenda-name">${esc(pName(a))}</div><div class="v3-agenda-meta">${esc(a.attentionType||a.type||'Sesión')} · ${esc(a.modality||'')} · ${money(a.cost)}</div></div><span class="v3-chip ${statusTone(a.status)}">${appStatus(a.status)}</span></div>`).join(''):'<div class="v3-empty">No hay citas programadas para hoy.</div>'}</div>
 <div class="v3-card"><div class="v3-card-head"><div><h3>Ingresos · últimos 7 días</h3><div class="v3-card-sub">Cobros registrados por día.</div></div><button class="v3-link-btn" onclick="switchTab('finanzas')">Ver finanzas</button></div><div class="v3-bars">${last7.map(x=>`<div class="v3-bar-wrap"><div class="v3-bar-value">${x.val?Math.round(x.val):''}</div><div class="v3-bar" style="height:${Math.max(4,(x.val/max)*100)}%"></div><div class="v3-bar-label">${x.d.toLocaleDateString('es-PE',{weekday:'short'}).slice(0,2)}</div></div>`).join('')}</div></div></div>
 <div class="v3-grid-3"><div class="v3-card"><div class="v3-card-head"><div><h3>Prioridades</h3><div class="v3-card-sub">Seguimientos que requieren acción.</div></div><button class="v3-link-btn" onclick="switchTab('alertas')">Todas</button></div>${[...unpaid.map(x=>['wallet',`${x.p.name}: pago pendiente`,money(x.amount)]),...noFollow.map(x=>['bell',`${x.p.name}: sin seguimiento`,`${ageDays(x.last.date)} días desde última atención`])].slice(0,5).map(x=>`<div class="v3-alert-row"><span class="v3-alert-ico">${ico(x[0])}</span><div><strong>${esc(x[1])}</strong><span>${esc(x[2])}</span></div></div>`).join('')||'<div class="v3-empty">No hay prioridades críticas.</div>'}</div>
 <div class="v3-card"><div class="v3-card-head"><div><h3>Continuidad clínica</h3><div class="v3-card-sub">Estado documental.</div></div></div><div class="v3-mini-stat"><strong>${st.histories.length}</strong><span>Historias registradas</span></div><div class="v3-mini-stat" style="margin-top:8px"><strong>${st.notes.length}</strong><span>Notas clínicas</span></div><button class="v3-primary" style="width:100%;justify-content:center;margin-top:10px" onclick="switchTab('clinica')">${ico('clinical')}Gestión clínica</button></div>
 <div class="v3-card"><div class="v3-card-head"><div><h3>Accesos rápidos</h3><div class="v3-card-sub">Acciones frecuentes.</div></div></div><button class="v3-secondary" style="width:100%;justify-content:flex-start;margin-bottom:7px" onclick="openPatientModal()">${ico('users')}Nuevo paciente</button><button class="v3-secondary" style="width:100%;justify-content:flex-start;margin-bottom:7px" onclick="switchTab('sesiones')">${ico('session')}Ver sesiones</button><button class="v3-secondary" style="width:100%;justify-content:flex-start" onclick="openV3EvaluationModal()">${ico('test')}Registrar evaluación</button></div></div></div>`};

window.renderV3Sessions=function(){const apps=S().appointments.filter(isValidApp),term=(q('v3-session-search')?.value||'').toLowerCase(),status=q('v3-session-status')?.value||'all';let list=apps.filter(a=>status==='all'||a.status===status).filter(a=>!term||pName(a).toLowerCase().includes(term)).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));const completed=apps.filter(a=>a.status==='completada').length,inSession=apps.filter(a=>a.status==='in_session').length,waiting=apps.filter(a=>a.status==='arrived').length,noShow=apps.filter(a=>a.status==='no_asistio').length;q('v3-session-kpis').innerHTML=kpi('Completadas',completed,'check')+kpi('En sesión',inSession,'session')+kpi('En espera',waiting,'reception')+kpi('No asistió',noShow,'x');q('v3-session-table').innerHTML=list.length?`<div class="v3-table-wrap"><table class="v3-table"><thead><tr><th>Fecha</th><th>Paciente</th><th>Atención</th><th>Estado</th><th>Pago</th><th>Acciones</th></tr></thead><tbody>${list.slice(0,100).map(a=>`<tr><td>${dateLabel(a.date)}<br><small>${esc(a.time||'')}</small></td><td class="name">${esc(pName(a))}</td><td>${esc(a.attentionType||'Sesión')} · ${esc(a.modality||'')}</td><td><span class="v3-chip ${statusTone(a.status)}">${appStatus(a.status)}</span></td><td>${a.paymentStatus==='pagado'?'<span class="v3-chip green">Pagado</span>':'<span class="v3-chip amber">Pendiente</span>'}</td><td><div class="v3-table-actions"><button class="v3-icon-action" title="Paciente 360" onclick="openV3Patient('${a.patientId}')">${ico('users')}</button><button class="v3-icon-action" title="Historia clínica" onclick="openClinicalHistory('${a.patientId}')">${ico('clinical')}</button><button class="v3-icon-action" title="Editar cita" onclick="editAppointment('${a.id}')">${ico('edit')}</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="v3-empty">No hay sesiones para los filtros seleccionados.</div>'};
function allEvaluations(){return S().patients.flatMap(p=>(p.evaluations||[]).map(e=>({...e,patientId:p.id,patientName:p.name})))}
window.renderV3Evaluations=function(){const all=allEvaluations(),term=(q('v3-eval-search')?.value||'').toLowerCase(),list=all.filter(e=>!term||String(e.patientName||'').toLowerCase().includes(term)||String(e.type||'').toLowerCase().includes(term)).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))),types=new Set(all.map(e=>e.type)).size,patients=new Set(all.map(e=>e.patientId)).size;q('v3-eval-kpis').innerHTML=kpi('Evaluaciones',all.length,'test')+kpi('Pacientes evaluados',patients,'users')+kpi('Instrumentos',types,'file')+kpi('Este mes',all.filter(e=>String(e.date||'').startsWith(limaToday().slice(0,7))).length,'calendar');q('v3-eval-table').innerHTML=list.length?`<div class="v3-table-wrap"><table class="v3-table"><thead><tr><th>Fecha</th><th>Paciente</th><th>Instrumento</th><th>Resultado</th><th>Interpretación</th><th>Acciones</th></tr></thead><tbody>${list.map(e=>{const max=Number(e.max||100),score=Number(e.score||0),pct=Math.max(0,Math.min(100,score/max*100));return `<tr><td>${dateLabel(e.date)}</td><td class="name">${esc(e.patientName)}</td><td>${esc(e.type||'Evaluación')}</td><td><div class="v3-eval-score"><span class="v3-score-ring" style="--pct:${pct}%"><strong>${score}</strong></span><span>/ ${max}</span></div></td><td>${esc(e.interpretation||'Sin interpretación')}</td><td><button class="v3-icon-action" onclick="openV3Patient('${e.patientId}')">${ico('users')}</button></td></tr>`}).join('')}</tbody></table></div>`:'<div class="v3-empty">Todavía no hay evaluaciones registradas.</div>'};
window.openV3EvaluationModal=function(pid=''){const options=S().patients.map(p=>`<option value="${p.id}" ${String(p.id)===String(pid)?'selected':''}>${esc(p.name)}</option>`).join('');q('v3-form-modal').innerHTML=`<h3>Registrar evaluación</h3><p class="v3-card-sub">Se guarda como un campo adicional en la ficha actual del paciente; no mueve datos existentes.</p><div class="v3-form-grid"><div class="v3-field full"><label>Paciente</label><select id="v3-eval-patient">${options}</select></div><div class="v3-field"><label>Instrumento</label><select id="v3-eval-type" onchange="v3EvalPreset()"><option value="PHQ-9">PHQ-9</option><option value="GAD-7">GAD-7</option><option value="PSS-14">PSS-14</option><option value="DASS-21">DASS-21</option><option value="Rosenberg">Rosenberg</option><option value="Personalizada">Personalizada</option></select></div><div class="v3-field"><label>Fecha</label><input type="date" id="v3-eval-date" value="${limaToday()}"></div><div class="v3-field"><label>Puntaje</label><input type="number" id="v3-eval-score" min="0" value="0"></div><div class="v3-field"><label>Máximo</label><input type="number" id="v3-eval-max" min="1" value="27"></div><div class="v3-field full"><label>Interpretación / observación</label><textarea id="v3-eval-interpretation" placeholder="Ej. Moderado, seguimiento recomendado..."></textarea></div></div><div class="v3-head-actions" style="justify-content:flex-end;margin-top:15px"><button class="v3-secondary" onclick="closeV3Form()">Cancelar</button><button class="v3-primary" onclick="saveV3Evaluation()">Guardar evaluación</button></div>`;q('v3-form-overlay').classList.remove('hidden')};
window.v3EvalPreset=function(){const m={'PHQ-9':27,'GAD-7':21,'PSS-14':56,'DASS-21':63,'Rosenberg':40};const v=q('v3-eval-type')?.value;if(m[v])q('v3-eval-max').value=m[v]};
window.saveV3Evaluation=async function(){const pid=q('v3-eval-patient').value,p=patient(pid);if(!p)return;const item={id:'eval_'+Date.now(),type:q('v3-eval-type').value,date:q('v3-eval-date').value,score:Number(q('v3-eval-score').value||0),max:Number(q('v3-eval-max').value||1),interpretation:q('v3-eval-interpretation').value.trim(),createdAt:new Date().toISOString()};try{await window.updatePatientV3(pid,{evaluations:[...(p.evaluations||[]),item]});closeV3Form();toast('Evaluación registrada');setTimeout(renderV3Evaluations,400)}catch(e){toast(e.message||'No se pudo guardar','err')}};
function allDocs(){return S().patients.flatMap(p=>(p.documents||[]).map(d=>({...d,patientId:p.id,patientName:p.name})))}
window.renderV3Documents=function(){const all=allDocs(),term=(q('v3-doc-search')?.value||'').toLowerCase(),list=all.filter(d=>!term||[d.patientName,d.title,d.type].some(x=>String(x||'').toLowerCase().includes(term))).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));q('v3-doc-kpis').innerHTML=kpi('Documentos',all.length,'folder')+kpi('Pacientes con archivos',new Set(all.map(d=>d.patientId)).size,'users')+kpi('Informes',all.filter(d=>String(d.type).toLowerCase().includes('informe')).length,'report')+kpi('Consentimientos',all.filter(d=>String(d.type).toLowerCase().includes('consent')).length,'file');q('v3-doc-table').innerHTML=list.length?`<div class="v3-table-wrap"><table class="v3-table"><thead><tr><th>Fecha</th><th>Paciente</th><th>Documento</th><th>Tipo</th><th>Acciones</th></tr></thead><tbody>${list.map(d=>`<tr><td>${dateLabel(d.date)}</td><td class="name">${esc(d.patientName)}</td><td>${esc(d.title)}</td><td><span class="v3-chip blue">${esc(d.type||'Documento')}</span></td><td><div class="v3-table-actions">${d.url?`<a class="v3-icon-action" target="_blank" rel="noopener" href="${esc(d.url)}" title="Abrir">${ico('arrow')}</a>`:''}<button class="v3-icon-action" onclick="openV3Patient('${d.patientId}')">${ico('users')}</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="v3-empty">No hay documentos registrados. Puedes añadir enlaces a archivos almacenados en Drive u otro repositorio seguro.</div>'};
window.openV3DocumentModal=function(pid=''){const options=S().patients.map(p=>`<option value="${p.id}" ${String(p.id)===String(pid)?'selected':''}>${esc(p.name)}</option>`).join('');q('v3-form-modal').innerHTML=`<h3>Añadir documento</h3><p class="v3-card-sub">Registra el enlace y metadatos sin alterar la estructura actual de Firebase.</p><div class="v3-form-grid"><div class="v3-field full"><label>Paciente</label><select id="v3-doc-patient">${options}</select></div><div class="v3-field"><label>Título</label><input id="v3-doc-title" placeholder="Consentimiento informado"></div><div class="v3-field"><label>Tipo</label><select id="v3-doc-type"><option>Consentimiento</option><option>Informe psicológico</option><option>Receta</option><option>Evaluación</option><option>Otro</option></select></div><div class="v3-field"><label>Fecha</label><input type="date" id="v3-doc-date" value="${limaToday()}"></div><div class="v3-field"><label>URL segura</label><input id="v3-doc-url" placeholder="https://..."></div></div><div class="v3-head-actions" style="justify-content:flex-end;margin-top:15px"><button class="v3-secondary" onclick="closeV3Form()">Cancelar</button><button class="v3-primary" onclick="saveV3Document()">Guardar documento</button></div>`;q('v3-form-overlay').classList.remove('hidden')};
window.saveV3Document=async function(){const pid=q('v3-doc-patient').value,p=patient(pid);if(!p)return;const item={id:'doc_'+Date.now(),title:q('v3-doc-title').value.trim(),type:q('v3-doc-type').value,date:q('v3-doc-date').value,url:q('v3-doc-url').value.trim(),createdAt:new Date().toISOString()};if(!item.title)return toast('Ingresa un título','err');try{await window.updatePatientV3(pid,{documents:[...(p.documents||[]),item]});closeV3Form();toast('Documento añadido');setTimeout(renderV3Documents,400)}catch(e){toast(e.message||'No se pudo guardar','err')}};
window.closeV3Form=()=>q('v3-form-overlay')?.classList.add('hidden');

window.openV3Patient=function(pid,tab='resumen'){const p=patient(pid);if(!p)return;window.__v3Patient=pid;q('v3-drawer-backdrop').classList.remove('hidden');q('v3-patient-drawer').classList.remove('hidden');renderV3PatientTab(tab)};window.closeV3Patient=function(){q('v3-drawer-backdrop')?.classList.add('hidden');q('v3-patient-drawer')?.classList.add('hidden')};
window.renderV3PatientTab=function(tab='resumen'){const p=patient(window.__v3Patient);if(!p)return;const pid=p.id,apps=patientApps(pid).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)),evals=p.evaluations||[],docs=p.documents||[],notes=S().notes.filter(n=>String(n.patientId||n.pid||'')===String(pid)),last=lastApp(pid),next=nextApp(pid);let body='';if(tab==='resumen')body=`<div class="v3-patient-kpis"><div class="v3-mini-stat"><strong>${completedCount(pid)}</strong><span>Sesiones</span></div><div class="v3-mini-stat"><strong>${money(debt(pid))}</strong><span>Saldo</span></div><div class="v3-mini-stat"><strong>${evals.length}</strong><span>Evaluaciones</span></div><div class="v3-mini-stat"><strong>${docs.length}</strong><span>Documentos</span></div></div><div class="v3-grid-2"><div class="v3-card"><h3>Actividad reciente</h3><div class="v3-timeline" style="margin-top:14px">${apps.slice(0,8).map(a=>`<div class="v3-timeline-item"><strong>${dateLabel(a.date)} · ${esc(a.time||'')} · ${appStatus(a.status)}</strong><span>${esc(a.attentionType||'Sesión')} · ${esc(a.modality||'')} · ${money(a.cost)}</span></div>`).join('')||'<div class="v3-empty">Sin actividad.</div>'}</div></div><div class="v3-card"><h3>Resumen clínico-administrativo</h3><div class="v3-alert-row"><span class="v3-alert-ico">${ico('calendar')}</span><div><strong>Próxima cita</strong><span>${next?dateLabel(next.date)+' · '+(next.time||''):'Sin próxima cita'}</span></div></div><div class="v3-alert-row"><span class="v3-alert-ico">${ico('clinical')}</span><div><strong>Historia clínica</strong><span>${hasHistory(pid)?'Registrada':'Pendiente'}</span></div></div><div class="v3-alert-row"><span class="v3-alert-ico">${ico('file')}</span><div><strong>Notas clínicas</strong><span>${notes.length} registro(s)</span></div></div></div></div>`;
 if(tab==='sesiones')body=`<div class="v3-card"><div class="v3-card-head"><h3>Sesiones y citas</h3><button class="v3-primary" onclick="closeV3Patient();openAppointmentModal()">${ico('plus')}Nueva cita</button></div>${apps.length?apps.map(a=>`<div class="v3-agenda-row"><div class="v3-agenda-time">${dateLabel(a.date)}</div><div class="v3-agenda-line"></div><div><div class="v3-agenda-name">${esc(a.time||'')} · ${appStatus(a.status)}</div><div class="v3-agenda-meta">${esc(a.modality||'')} · ${money(a.cost)}</div></div><button class="v3-icon-action" onclick="editAppointment('${a.id}')">${ico('edit')}</button></div>`).join(''):'<div class="v3-empty">Sin sesiones.</div>'}</div>`;
 if(tab==='clinica')body=`<div class="v3-card"><div class="v3-card-head"><div><h3>Gestión clínica</h3><div class="v3-card-sub">Historia y evolución existente.</div></div><button class="v3-primary" onclick="openClinicalHistory('${pid}')">${ico('clinical')}Abrir historia</button></div><div class="v3-patient-kpis"><div class="v3-mini-stat"><strong>${hasHistory(pid)?'Sí':'No'}</strong><span>Historia clínica</span></div><div class="v3-mini-stat"><strong>${notes.length}</strong><span>Notas</span></div><div class="v3-mini-stat"><strong>${last?dateLabel(last.date):'—'}</strong><span>Última sesión</span></div><div class="v3-mini-stat"><strong>${p.leadStatus||'nuevo'}</strong><span>Estado CRM</span></div></div></div>`;
 if(tab==='evaluaciones')body=`<div class="v3-card"><div class="v3-card-head"><h3>Evaluaciones</h3><button class="v3-primary" onclick="openV3EvaluationModal('${pid}')">${ico('plus')}Registrar</button></div>${evals.length?evals.slice().reverse().map(e=>`<div class="v3-alert-row"><span class="v3-alert-ico">${ico('test')}</span><div><strong>${esc(e.type)} · ${e.score}/${e.max}</strong><span>${dateLabel(e.date)} · ${esc(e.interpretation||'Sin interpretación')}</span></div></div>`).join(''):'<div class="v3-empty">Sin evaluaciones registradas.</div>'}</div>`;
 if(tab==='documentos')body=`<div class="v3-card"><div class="v3-card-head"><h3>Documentos</h3><button class="v3-primary" onclick="openV3DocumentModal('${pid}')">${ico('plus')}Añadir</button></div>${docs.length?docs.slice().reverse().map(d=>`<div class="v3-alert-row"><span class="v3-alert-ico">${ico('folder')}</span><div style="flex:1"><strong>${esc(d.title)}</strong><span>${esc(d.type||'Documento')} · ${dateLabel(d.date)}</span></div>${d.url?`<a class="v3-icon-action" target="_blank" rel="noopener" href="${esc(d.url)}">${ico('arrow')}</a>`:''}</div>`).join(''):'<div class="v3-empty">Sin documentos registrados.</div>'}</div>`;
 if(tab==='finanzas')body=`<div class="v3-card"><h3>Estado financiero del paciente</h3><div class="v3-patient-kpis" style="margin-top:12px"><div class="v3-mini-stat"><strong>${money(apps.filter(a=>a.paymentStatus==='pagado').reduce((n,a)=>n+Number(a.cost||0),0))}</strong><span>Pagado</span></div><div class="v3-mini-stat"><strong>${money(debt(pid))}</strong><span>Pendiente</span></div><div class="v3-mini-stat"><strong>${apps.filter(a=>a.paymentStatus==='pagado').length}</strong><span>Operaciones</span></div><div class="v3-mini-stat"><strong>${(p.packages||[]).length}</strong><span>Paquetes</span></div></div></div>`;
 q('v3-patient-content').innerHTML=`<div class="v3-drawer-head"><div class="v3-drawer-top"><div style="display:flex;gap:12px;align-items:center"><div class="v3-avatar">${initials(p.name)}</div><div><h2>${esc(p.name||'Paciente')}</h2><p>${esc(p.phone||'Sin teléfono')} · ${esc(p.dni||'Sin DNI')} · ${esc(p.leadStatus||'nuevo')}</p></div></div><button class="v3-hero-btn ghost" style="width:36px;padding:0;justify-content:center" onclick="closeV3Patient()">${ico('x')}</button></div><div class="v3-drawer-tabs">${[['resumen','Resumen'],['sesiones','Sesiones'],['clinica','Clínica'],['evaluaciones','Evaluaciones'],['documentos','Documentos'],['finanzas','Finanzas']].map(x=>`<button class="${tab===x[0]?'active':''}" onclick="renderV3PatientTab('${x[0]}')">${x[1]}</button>`).join('')}</div></div><div class="v3-drawer-body">${body}<div class="v3-head-actions" style="margin-top:12px"><button class="v3-secondary" onclick="closeV3Patient();editPatient('${pid}')">${ico('edit')}Editar datos</button><button class="v3-secondary" onclick="closeV3Patient();openPatientHistory('${pid}')">${ico('calendar')}Historial</button></div></div>`};

function financeRange(){const st=S(),ref=st.financeReferenceDate||limaToday(),period=st.financePeriod||'todo';if(period==='todo')return [null,null];if(period==='personalizado')return [st.financeCustomStart,st.financeCustomEnd];const d=new Date(ref+'T00:00:00');if(period==='dia')return [ref,ref];if(period==='semana'){const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);const a=d.toLocaleDateString('en-CA');d.setDate(d.getDate()+6);return[a,d.toLocaleDateString('en-CA')]}if(period==='mes'){const y=d.getFullYear(),m=d.getMonth();return[new Date(y,m,1).toLocaleDateString('en-CA'),new Date(y,m+1,0).toLocaleDateString('en-CA')]}return[null,null]}
function renderV3FinanceInsights(){const sec=q('sec-finanzas');if(!sec)return;let root=q('v3-finance-insights-root');if(!root){root=document.createElement('div');root.id='v3-finance-insights-root';sec.insertBefore(root,sec.children[1]||null)}const [from,to]=financeRange();let apps=S().appointments.filter(isValidApp).filter(a=>a.status!=='cancelada'&&(!from||a.date>=from)&&(!to||a.date<=to));const paid=apps.filter(a=>a.paymentStatus==='pagado'),collected=paid.reduce((n,a)=>n+Number(a.cost||0),0),projected=apps.filter(a=>!['cancelada','no_asistio'].includes(a.status)).reduce((n,a)=>n+Number(a.cost||0),0),pending=apps.filter(a=>a.paymentStatus!=='pagado'&&!['cancelada','no_asistio'].includes(a.status)).reduce((n,a)=>n+Number(a.cost||0)-Number(a.paidAmount||0),0);const byMethod={};paid.forEach(a=>{const m=a.paymentMethod||a.payMethod||'Sin especificar';byMethod[m]=(byMethod[m]||0)+Number(a.cost||0)});const total=Math.max(1,Object.values(byMethod).reduce((a,b)=>a+b,0));const buckets={};apps.forEach(a=>{const k=(a.date||'').slice(5);if(k)buckets[k]=(buckets[k]||0)+(a.paymentStatus==='pagado'?Number(a.cost||0):0)});const entries=Object.entries(buckets).sort().slice(-12),max=Math.max(1,...entries.map(x=>x[1]));root.innerHTML=`<div class="v3-finance-insights"><div class="v3-card"><div class="v3-card-head"><div><h3>Rendimiento del periodo</h3><div class="v3-card-sub">Cobrado ${money(collected)} · Pendiente ${money(pending)} · Proyectado ${money(projected)}</div></div></div><div class="v3-bars">${entries.length?entries.map(([d,v])=>`<div class="v3-bar-wrap"><div class="v3-bar-value">${v?Math.round(v):''}</div><div class="v3-bar" style="height:${Math.max(4,v/max*100)}%"></div><div class="v3-bar-label">${esc(d)}</div></div>`).join(''):'<div class="v3-empty">Sin movimientos en el periodo.</div>'}</div></div><div class="v3-card"><div class="v3-card-head"><div><h3>Métodos de pago</h3><div class="v3-card-sub">Distribución de cobros.</div></div></div><div class="v3-pay-methods">${Object.entries(byMethod).sort((a,b)=>b[1]-a[1]).map(([m,v])=>`<div class="v3-method-row"><span>${esc(m)}</span><div class="v3-method-track"><div class="v3-method-fill" style="width:${v/total*100}%"></div></div><strong>${Math.round(v/total*100)}%</strong></div>`).join('')||'<div class="v3-empty">Sin cobros registrados.</div>'}</div></div></div>`}

const oldOpen360=window.openPatient360;window.openPatient360=function(pid){openV3Patient(pid)};
function installRouter(){const old=window.switchTab;window.__v3OldSwitch=old;window.switchTab=function(target){const extra=['sesiones','evaluaciones','documentos'];if(extra.includes(target)){document.querySelectorAll('main>section[id^="sec-"]').forEach(s=>s.classList.add('hidden'));q('sec-'+target)?.classList.remove('hidden');document.querySelectorAll('[data-v2-nav]').forEach(b=>b.classList.toggle('v2-nav-active',b.dataset.v2Nav===target));if(target==='sesiones')renderV3Sessions();if(target==='evaluaciones')renderV3Evaluations();if(target==='documentos')renderV3Documents();try{localStorage.setItem('agendaV3LastTab',target)}catch(_){}return}old?.(target);if(target==='inicio')setTimeout(renderV3Dashboard,10);if(target==='finanzas')setTimeout(renderV3FinanceInsights,30);};const oldFin=window.setFinancePeriod;if(oldFin)window.setFinancePeriod=function(...args){const r=oldFin.apply(this,args);setTimeout(renderV3FinanceInsights,30);return r}}
function bindKeys(){document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openV3Search()}if(e.key==='Escape'){closeV3Search();closeV3Form();closeV3Patient()}})}
function refreshVisible(){if(!q('app-container')||q('app-container').classList.contains('hidden'))return;const vis=[...document.querySelectorAll('main>section[id^="sec-"]')].find(x=>!x.classList.contains('hidden'))?.id?.replace('sec-','');if(vis==='inicio')renderV3Dashboard();if(vis==='sesiones')renderV3Sessions();if(vis==='evaluaciones')renderV3Evaluations();if(vis==='documentos')renderV3Documents();if(vis==='finanzas')renderV3FinanceInsights()}
function boot(){injectSymbols();installShell();injectSections();installOverlays();installRouter();bindKeys();setTimeout(()=>{if(!q('app-container')?.classList.contains('hidden'))renderV3Dashboard()},600);setInterval(refreshVisible,12000)}
document.addEventListener('DOMContentLoaded',boot);
})();
