const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),D=require('../domain.cjs');
function harness({consent=true,status='pendiente',failure=false,changeConsent=false}={}){
 const clock=Date.parse('2026-10-09T17:05:00Z'),root='artifacts/'+D.APP_ID+'/users/u',records=new Map([[root+'/appointments/a',{patientId:'p',patientName:'Paciente',date:'2026-10-09',time:'13:00',status,cost:50,paymentStatus:'pendiente'}],[root+'/patients/p',{name:'Paciente',phone:'999999999',whatsappOptIn:consent} ],['_consultorioAutomation/u',{enabled:true,leadMinutes:60}]]);let lock=Promise.resolve();const requests=[],reads=[];
 const snapshot=path=>({id:path.split('/').at(-1),exists:records.has(path),data:()=>records.get(path),ref:doc(path)});
 const collection=path=>({where(){return this},limit(){return this},orderBy(){return this},doc:id=>doc(path+'/'+id),async get(){reads.push(path);const docs=[...records.keys()].filter(key=>key.startsWith(path+'/')&&key.slice(path.length+1).indexOf('/')<0).map(snapshot);return {docs,size:docs.length};}});
 const doc=path=>({path,async get(){return snapshot(path)},collection:name=>collection(path+'/'+name),async set(value){records.set(path,{...records.get(path),...value})},async update(value){records.set(path,{...records.get(path),...value})}});
 const db={doc,async runTransaction(fn){let release;const next=new Promise(r=>release=r),prev=lock;lock=next;await prev;try{if(changeConsent)records.get(root+'/patients/p').whatsappOptIn=false;return await fn({get:ref=>ref.get(),set:(ref,value)=>records.set(ref.path,value)});}finally{release();}}};
 const params={CONSULTORIO_ALLOWED_UIDS:'u',META_PHONE_NUMBER_ID:'123456',META_GRAPH_VERSION:'v23.0',META_REMINDER_TEMPLATE:'cita',META_TEMPLATE_LANGUAGE:'es_PE',GEMINI_MODEL:'test-model'};class Clock extends Date{constructor(...args){super(...(args.length?args:[clock]));}static now(){return clock;}}
 const exports={};const context={exports,Date:Clock,AbortSignal,console,fetch:async(url,options)=>{requests.push({url,options});if(failure)throw new Error('timeout');return {ok:true,status:200,json:async()=>url.includes('generativelanguage')?{candidates:[{content:{parts:[{text:JSON.stringify({action:'nota',patientId:'otro',date:'2026-10-09',note:'test',message:'nota'})}]}}]}:{messages:[{id:'mock-message'}]}};},require:name=>{if(name==='./domain.cjs')return D;if(name==='firebase-admin/app')return {initializeApp(){}};if(name==='firebase-admin/firestore')return {getFirestore:()=>db};if(name==='firebase-functions/v2/https')return {onCall:(_opts,fn)=>fn,HttpsError:class extends Error{constructor(code,message){super(message);this.code=code}}};if(name==='firebase-functions/v2/scheduler')return {onSchedule:(_opts,fn)=>fn};if(name==='firebase-functions/params')return {defineString:name=>({value:()=>params[name]}),defineSecret:()=>({value:()=> 'FAKE_TEST_VALUE'})};throw new Error(name);}};
 vm.runInNewContext(fs.readFileSync(require.resolve('../index.cjs'),'utf8'),context);return {exports,requests,records,reads};
}
test('dos procesos concurrentes reclaman un solo envío',async()=>{const h=harness();await Promise.all([h.exports.whatsappReminders(),h.exports.whatsappReminders()]);assert.equal(h.requests.length,1);assert.equal([...h.records.values()].filter(x=>x.status==='accepted').length,1);assert(!h.requests[0].options.body.includes('evolucion'));});
test('omite falta de consentimiento y citas canceladas',async()=>{for(const setup of [{consent:false},{status:'cancelada'},{status:'completada'}]){const h=harness(setup);await h.exports.whatsappReminders();assert.equal(h.requests.length,0);}});
test('revalida consentimiento antes de reclamar el envío',async()=>{const h=harness({changeConsent:true});await h.exports.whatsappReminders();assert.equal(h.requests.length,0);});
test('resultado ambiguo requiere revisión, no reenvía al reintentar',async()=>{const h=harness({failure:true});await h.exports.whatsappReminders();await h.exports.whatsappReminders();assert.equal(h.requests.length,1);assert([...h.records.values()].some(x=>x.status==='unknown'));});
test('rechaza cuenta ajena antes de leer o enviar',async()=>{const h=harness();await assert.rejects(h.exports.assistantPlan({auth:{uid:'other'},data:{message:'hola'}}),e=>e.code==='permission-denied');assert.equal(h.requests.length,0);assert.equal(h.reads.length,0);});
test('propuesta de paciente inexistente se convierte en aclaración; no carga historias',async()=>{const h=harness();const result=await h.exports.assistantPlan({auth:{uid:'u'},data:{message:'nota'}});assert.equal(result.action,'respuesta');assert(!h.reads.some(p=>/clinicalHistories|clinicalNotes/.test(p)));});
