const fs=require('fs'),assert=require('assert');
const {chromium:playwright}=require('playwright');
const http=require('http'),path=require('path');const root=path.resolve(__dirname,'..');const server=http.createServer((req,res)=>{let file=path.join(root,new URL(req.url,'http://localhost').pathname);if(file===root+'/')file=path.join(root,'index.html');try{const body=fs.readFileSync(file);const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'})[ext]||'application/octet-stream');res.end(body);}catch{res.statusCode=404;res.end();}});server.listen(8765,'127.0.0.1');

(async()=>{const browser=await playwright.launch({...(process.env.CRM_BROWSER_PATH?{executablePath:process.env.CRM_BROWSER_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process'],headless:true});const page=await browser.newPage({viewport:{width:1366,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{const snaps={};window.__snapshots=snaps;window.__writes=[];window.__notifications=[];window.SpeechRecognition=class{start(){this.onresult?.({results:[[{transcript:'dictado de prueba'}]]})}stop(){this.onend?.()}};window.Notification=class{static permission='granted';static async requestPermission(){return 'granted'}constructor(title,options){window.__notifications.push({title,options});}};window.__alerts=[];window.alert=message=>window.__alerts.push(message);window.confirm=()=>true;Object.assign(window,{initializeApp:()=>({}),getAuth:()=>({currentUser:{uid:'test',email:'profesional@example.test'}}),getFirestore:()=>({}),initializeAppCheck:()=>({}),ReCaptchaV3Provider:class{},EmailAuthProvider:{credential:()=>({})},onAuthStateChanged:(_a,cb)=>{window.__login=()=>cb({uid:'test',email:'profesional@example.test'});window.__logout=()=>cb(null);},collection:(...a)=>a.slice(1).join('/'),onSnapshot:(ref,cb,error)=>{snaps[ref.split('/').at(-1)]={cb,error};return ()=>{}},doc:(...args)=>args.slice(1).join('/'),setDoc:async(ref,data)=>window.__writes.push({ref,data}),updateDoc:async()=>{},deleteDoc:async()=>{},getDocs:async()=>({docs:[]}),runTransaction:async(_db,fn)=>{const staged=[];await fn({get:async ref=>{const id=ref.split('/').at(-1),value=window._profileState.appointments.find(a=>a.id===id);return {exists:()=>!!value,data:()=>value}},update:(ref,patch)=>staged.push({ref,patch})});for(const entry of staged){const id=entry.ref.split('/').at(-1),rows=window._profileState.appointments.map(a=>a.id===id?{...a,...entry.patch}:a);snaps.appointments.cb({docs:rows.map(row=>({id:row.id,data:()=>row}))});}},signOut:async()=>{},signInWithEmailAndPassword:async()=>{},sendPasswordResetEmail:async()=>{},updatePassword:async()=>{},verifyPasswordResetCode:async()=>{},confirmPasswordReset:async()=>{},reauthenticateWithCredential:async()=>{}});});
await page.route('**/*',async route=>{const u=route.request().url();if(u.startsWith('http://127.0.0.1:8765/js/app.js'))return route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(root,'js/app.js'),'utf8').replace(/import\s+[\s\S]*?from\s+"https:[^"]+";/g,'')});if(u.startsWith('https://cdn.tailwindcss.com')){if(process.env.CRM_TAILWIND_FIXTURE)return route.fulfill({contentType:'text/javascript',body:fs.readFileSync(process.env.CRM_TAILWIND_FIXTURE,'utf8')});return route.continue();}if(!u.startsWith('http://127.0.0.1:8765/'))return route.fulfill({contentType:u.includes('googleapis')?'text/css':'text/javascript',body:''});return route.continue();});
await page.addInitScript(()=>{window.__calls=[];window.callConsultorioFunction=async(name,data)=>{window.__calls.push({name,data});if(name==='integrationStatus')return {aiConfigured:true,whatsappConfigured:true,enabled:false,leadMinutes:60,jobs:[]};if(name==='assistantPlan'&&window.__nextPlan)return window.__nextPlan;if(name==='assistantPlan')return {action:'pago',message:'Abono de prueba',appointmentId:'a1',patientId:'p1',patientName:'Paciente de prueba',amount:10,date:CRMCore.dateKey(),currency:'PEN',method:'Yape'};return {ok:true};};});
await page.goto('http://127.0.0.1:8765/' ,{waitUntil:'networkidle'});await page.waitForTimeout(2300);await page.evaluate(()=>{window.__login();const date=CRMCore.dateKey();const data={appointments:[{id:'a1',patientId:'p1',patientName:'Paciente de prueba',date,time:'10:30',status:'completada',cost:50,currency:'PEN',paidAmount:20,paymentStatus:'parcial',modality:'presencial'},{id:'a2',patientId:'p1',patientName:'Paciente de prueba',date,time:'17:00',status:'pendiente',cost:45,currency:'PEN',paymentStatus:'pendiente',modality:'virtual'}],patients:[{id:'p1',name:'Paciente de prueba',phone:'999999999',leadStatus:'recurrente'}],clinicalHistories:[],clinicalNotes:[{id:'n1',patientId:'p1',fecha:date,sesion:'1',evolucion:'Nota de prueba para revisión.'}]};for(const [key,rows] of Object.entries(data))__snapshots[key].cb({docs:rows.map(row=>({id:row.id,data:()=>row}))});});
await page.waitForTimeout(100);
await page.screenshot({path:'/tmp/crm-inicio-desktop.png',fullPage:true});
for(const route of ['citas','pacientes','alertas','finanzas','sesiones','asistente','herramientas']){await page.locator('.v2-sidebar [data-crm-route="'+route+'"]').click();assert.equal(await page.locator('#app-container>main>section:visible').count(),1,route);assert.equal(await page.locator('#sec-'+route).isVisible(),true,route);assert.equal(await page.locator('.crm-render-error').count(),0,route);}
await page.evaluate(()=>switchTab('citas'));await page.locator('[data-exp-action="select"]').first().click();assert((await page.locator('#appointments-list').textContent()).includes('Paciente de prueba'));await page.screenshot({path:'/tmp/crm-agenda-desktop.png',fullPage:true});
await page.evaluate(()=>switchTab('finanzas'));assert((await page.locator('#crm-finance-results').textContent()).includes('20.00'));await page.screenshot({path:'/tmp/crm-finanzas-desktop.png',fullPage:true});
await page.locator('#crm-finance-results [data-exp-action="pay"]').first().click();assert(await page.locator('#elo-payment-form').isVisible());await page.fill('#elo-payment-amount','10');await page.locator('#elo-payment-form button').click();assert.equal(await page.evaluate(()=>_profileState.appointments.find(a=>a.id==='a1').paidAmount),30);assert.equal(await page.evaluate(()=>_profileState.appointments.find(a=>a.id==='a1').paymentHistory.length),1);
await page.evaluate(()=>{window.__wa=[];window.open=(url)=>{__wa.push(url);return null;};switchTab('alertas');});await page.locator('[data-crm-action="whatsapp"]').first().click();assert((await page.evaluate(()=>__wa[0])).startsWith('https://wa.me/51999999999?text='));assert.equal(await page.locator('#elo-wa-reminder-summary').count(),0);
await page.evaluate(()=>switchTab('asistente'));await page.locator('#sec-asistente [data-crm-action="assistant"]').click();assert(await page.locator('#assistant-modal').isVisible());await page.evaluate(()=>closeAssistantModal());assert.equal(await page.locator('#elo-assistant-form').count(),0);
await page.evaluate(()=>switchTab('reportes'));await page.locator('[data-crm-action="legacy-reports"]').click();assert(await page.locator('#print-modal').isVisible());await page.evaluate(()=>closePrintModal());
await page.evaluate(()=>{const row={id:'a3',patientId:'p1',patientName:'Cita siguiente día',date:CRMCore.dateKey(new Date(Date.now()+86400000)),time:'17:00',status:'pendiente',cost:45};const rows=[..._profileState.appointments,row];__snapshots.appointments.cb({docs:rows.map(a=>({id:a.id,data:()=>a}))});switchTab('citas');setCitasView('semana');});assert((await page.locator('#appointments-list').textContent()).includes('Cita siguiente día'));await page.evaluate(()=>setCitasView('dia'));
await page.evaluate(()=>switchTab('sesiones'));await page.selectOption('#crm-notes-patient','p1');await page.locator('#crm-new-note summary').click();await page.fill('#crm-note-text','Evolución guardada desde prueba.');await page.fill('#crm-note-session','2');await page.locator('#crm-note-form button').click();assert((await page.locator('#crm-note-result').textContent()).includes('guardada'));assert.equal(await page.evaluate(()=>__writes.filter(x=>x.ref.includes('clinicalNotes')).length),1);
await page.setViewportSize({width:390,height:844});for(const route of ['inicio','citas','pacientes','finanzas','herramientas']){await page.locator('.v2-mobile-nav [data-crm-route="'+route+'"]').click();assert.equal(await page.locator('#sec-'+route).isVisible(),true);if(route==='citas'){const overlap=await page.locator('.v31-appointment-card').evaluateAll(cards=>cards.some(card=>card.querySelector('.v31-appointment-actions-primary').getBoundingClientRect().top<card.querySelector('.v31-badge-row').getBoundingClientRect().bottom));assert.equal(overlap,false,'mobile action buttons overlap');}const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert(overflow<=2,route+' mobile overflow '+overflow);await page.screenshot({path:'/tmp/crm-'+route+'-mobile.png',fullPage:true});}
await page.evaluate(()=>switchTab('sesiones'));await page.selectOption('#crm-notes-patient','p1');assert((await page.locator('#crm-note-list').textContent()).includes('Sesión 1'));
await page.evaluate(()=>{localStorage.setItem('consultorio_reminders_test',JSON.stringify({enabled:true,minutes:30}));const when=new Date(Date.now()+20*60000);const row={id:'notify1',patientId:'p1',patientName:'Paciente privado',date:CRMCore.dateKey(when),time:when.toLocaleTimeString('en-GB',{timeZone:'America/Lima',hour:'2-digit',minute:'2-digit'}),cost:50,status:'pendiente'};for(let i=0;i<2;i++)__snapshots.appointments.cb({docs:[{id:row.id,data:()=>row}]});});assert.equal(await page.evaluate(()=>__notifications.length),1);assert.equal(await page.evaluate(()=>__notifications[0].options.body.includes('Paciente privado')),false);
await page.evaluate(()=>__logout());assert.equal(await page.locator('#app-container').isVisible(),false);assert.equal(await page.locator('#crm-notes-main').count(),0);
assert.deepEqual(errors,[]);console.log('PASS Chromium: agenda list/detail/week, manual abono, manual WhatsApp, original assistant and original reports, notes, modules and mobile.');await browser.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
