const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const app = fs.readFileSync(path.join(root,'js/app.js'),'utf8');
const css = fs.readFileSync(path.join(root,'css/crm.css'),'utf8');
assert.match(app, /v23-manual-slot"><span>Ocupado<\/span>/, 'bloqueo manual se muestra como Ocupado');
assert.doesNotMatch(app, /v23-manual-slot"><span>Bloqueado<\/span>/, 'no mostrar Bloqueado en horario');
assert.match(app, /window\.removeAppointmentPermanently = async function\(aid\)/, 'función de eliminación');
assert.match(app, /onclick="removeAppointmentPermanently\('\$\{a\.id\}'\)"/, 'botón eliminar ligado');
assert.match(app, /runTransaction\(db, async tx =>/, 'transacción de eliminación');
for (const rule of ['original.packageId', 'financialHistory.length > 0', 'tx.set(logRef, audit)', 'tx.delete(ref)']) assert.ok(app.includes(rule), rule);
assert.match(css, /v85-delete-appointment/, 'botón destacado para móviles');
console.log('OK: horario ocupado y eliminación restringida con auditoría.');
